CREATE TABLE IF NOT EXISTS HTTPINFOS_LIST (
    ID SERIAL PRIMARY KEY     NOT NULL,
    URL TEXT,
    STATUS INT,
    H1 TEXT,
    TITLE TEXT,
    XPATH1 TEXT,
    XPATH2 TEXT,
    XPATH3 TEXT,
    XPATH4 TEXT,
    XPATH5 TEXT,
    TO_FETCH BOOLEAN 
) TABLESPACE mydbspace;

