CREATE TABLE IF NOT EXISTS HTTPINFOS_LIST (
    ID SERIAL PRIMARY KEY     NOT NULL,
    URL TEXT,
    STATUS INT,
    DESCRIPTION TEXT,
    H1 TEXT,
    TITLE TEXT,
    TO_FETCH BOOLEAN 
) TABLESPACE mydbspace;

