CREATE TABLE IF NOT EXISTS DUPLICATES (
    TITLE TEXT, 
    NB_URLS INT,
    URLS TEXT,
    DUPLICATE_TIME DATE,
    MAGAZIN TEXT,
    RAYON TEXT,
    PRODUCT TEXT
);


CREATE TABLE IF NOT EXISTS CURRENT_DUPLICATES (
    TITLE TEXT, 
    NB_URLS INT,
    URLS TEXT,
    DUPLICATE_TIME DATE,
    MAGAZIN TEXT,
    RAYON TEXT,
    PRODUCT TEXT
);
