CREATE TABLE IF NOT EXISTS SEARCHDEXING_KEYWORDS (
    KEYWORD VARCHAR(300) NOT NULL, 
    LANGUAGE VARCHAR(2),
    CDISCOUNT_URL TEXT,
    CDISCOUNT_SEARCH_VOLUME INT,
    AMAZON_SEARCH_VOLUME INT,
    RDC_SEARCH_VOLUME INT,
    CDISCOUNT_SEARCH_POSITION INT,
    AMAZON_SEARCH_POSITION INT,
    RDC_SEARCH_POSITION INT,
    MAGASIN VARCHAR(200),
    RAYON VARCHAR(200),
    PRODUIT VARCHAR(400)
);