UPDATE SEARCHDEXING_KEYWORDS as SD
SET AMAZON_SEARCH_VOLUME = PK.SEARCH_VOLUME,
    AMAZON_SEARCH_POSITION = PK.SEARCH_POSITION
FROM PRICING_KEYWORDS AS PK
WHERE SD.KEYWORD = PK.KEYWORD 
AND PK.DOMAIN='amazon.fr'

UPDATE SEARCHDEXING_KEYWORDS as SD
SET CDISCOUNT_SEARCH_VOLUME = PK.SEARCH_VOLUME,
    CDISCOUNT_SEARCH_POSITION = PK.SEARCH_POSITION
FROM PRICING_KEYWORDS AS PK
WHERE SD.KEYWORD = PK.KEYWORD 
AND PK.DOMAIN='cdiscount.com'


UPDATE SEARCHDEXING_KEYWORDS as SD
SET MAGASIN = PK.MAGASIN,
    RAYON = PK.RAYON,
    PRODUIT= PK.PRODUIT
FROM PRICING_KEYWORDS AS PK
WHERE SD.KEYWORD = PK.KEYWORD 
