CREATE TABLE IF NOT EXISTS GWT_DATA(
    WORD TEXT UNIQUE NOT NULL,
    NB_DOCUMENTS INT,
    DOC_LIST TEXT,
    LAST_UPDATE DATE
) TABLESPACE mydbspace;

CREATE TABLE IF NOT EXISTS CORPUS_WORDS_METADATA(
    THEMA TEXT,
    NB_TOTAL_DOCUMENTS INT
) TABLESPACE mydbspace;