CREATE TABLE IF NOT EXISTS HTTPINFOS_LIST (
    DID  INT,
    URL TEXT,
    #BUILDGROUP VARCHAR(10),
    #SOURCE TEXT,
    #SLICE TEXT,
    SCORE INT,
    #MASK TEXT 
    #SORT TEXT
    OFFER_PRODUCT_ID VARCHAR(100),
    OFFER_PRICE REAL,
    OFFER_SELLER_ID INT,
    PROXIMITY INT,
    CA1 REAL,
    CATEGORYWEIGHT REAL,
    CA14 REAL,
    CA7 REAL,
    TERMSCORE INT
);

DROP TABLE HTTPINFOS_LIST;

CREATE TABLE IF NOT EXISTS EXALEAD_RESULTS (
    REQUEST TEXT,
    DID  INT,
    URL TEXT,
    SCORE INT,
    OFFER_PRODUCT_ID VARCHAR(100),
    OFFER_PRICE REAL,
    OFFER_SELLER_ID INT,
    PROXIMITY INT,
    CA1 REAL,
    CATEGORYWEIGHT REAL,
    CA14 REAL,
    CA7 REAL,
    TERMSCORE INT
);
