update CATALOG set CATEGORIE_NIVEAU_4=CATEGORIE_NIVEAU_3 where CATEGORIE_NIVEAU_4=''
update CATALOG set CATEGORIE_NIVEAU_4=CATEGORIE_NIVEAU_2 where CATEGORIE_NIVEAU_4=''
update CATALOG set CATEGORIE_NIVEAU_4=CATEGORIE_NIVEAU_1 where CATEGORIE_NIVEAU_4=''