CREATE TABLE IF NOT EXISTS REFERENTIAL_FACETTES_LIST (
    ID SERIAL PRIMARY KEY     NOT NULL,
    URL TEXT,
    TO_FETCH BOOLEAN 
) TABLESPACE mydbspace;


CREATE TABLE IF NOT EXISTS REFERENTIAL_FACETTES_LIST_RESULTS (
    URL TEXT,
    MAGASIN VARCHAR(250),
    LEVEL_TWO VARCHAR(300),
    LEVEL_THREE VARCHAR(400),
    FACETTE_NAME VARCHAR(400),
    FACETTE_VALUE VARCHAR(250),
    FACETTE_COUNT INT,
    MARKETPLACE_FACETTE_COUNT INT,
    MARKETPLACE_QUOTE_PART NUMERIC,
    PRODUCTLIST_COUNT INT,
    IS_FACETTE_OPENED BOOLEAN,
    OPENED_URL TEXT
) TABLESPACE mydbspace;
