CREATE TABLE IF NOT EXISTS TRUST_RATING (
    SOURCE_URL TEXT,
    SOURCE_DOMAIN TEXT,
    NB_LINKS INT,
    NB_DOMAIN_LINKS INT,
    LINK_TRUSTFLOW INT,
    COMPUTED_TRUST_RATE_LINK INT,
    COMPUTED_TRUST_RATE_DOMAIN INT)
