select CURRENT_DUPLICATES.title as gwt_title,CURRENT_DUPLICATES.urls as gwt_urls, CURRENT_CONTINUOUS_DUPLICATES.title as cont_title,CURRENT_CONTINUOUS_DUPLICATES.urls as cont_urls INTO GWT_VS_CONTINUOUS from CURRENT_DUPLICATES FULL OUTER JOIN CURRENT_CONTINUOUS_DUPLICATES  on( CURRENT_CONTINUOUS_DUPLICATES.title=CURRENT_DUPLICATES.title)

select * from GWT_VS_CONTINUOUS where gwt_title is null;
select * from GWT_VS_CONTINUOUS where cont_title is null;