CREATE TABLE IF NOT EXISTS MAGASIN_PRODUITS(
    MAGASIN VARCHAR(100),
    RAYON VARCHAR(100),
    NB_SKUS_TOTAL INT,
    NB_SKUS_MP INT,
    NB_SKUS_CD INT,
    NB_SKUS_MIXTE INT,
    NB_OFFRE_EXCLU_MP INT,
    REPORT_DATE DATE,
    PRIMARY KEY(MAGASIN, RAYON, REPORT_DATE)
) TABLESPACE mydbspace;