Identifiant_Produit;Categorie1;Categorie2;Categorie3;Description;Libelle;Marque;Produit_Cdiscount;prix



CREATE TABLE IF NOT EXISTS TRAINING_DATA (
IDENTIFIANT_PRODUIT VARCHAR(50), 
CATEGORIE_1 VARCHAR(50), 
CATEGORIE_2 VARCHAR(50), 
CATEGORIE_3 VARCHAR(50), 
DESCRIPTION TEXT,
LIBELLE VARCHAR(200),
MARQUE VARCHAR(150),
PRODUIT_CDISCOUNT BOOLEAN,
PRIX NUMERIC,
IS_IN_TFIDF_INDEX BOOLEAN,
TO_FETCH BOOLEAN) TABLESPACE mydbspace

CREATE TABLE IF NOT EXISTS TRAINING_DATA (
    IDENTIFIANT_PRODUIT VARCHAR(100),
    CATEGORIE_1 TEXT,
    CATEGORIE_2 TEXT,
    CATEGORIE_3 TEXT,
    DESCRIPTION VARCHAR(100),
    LIBELLE VARCHAR(100),
    MARQUE VARCHAR(100),
    PRODUIT_CDISCOUNT VARCHAR(10),
    PRIX NUMERIC,
    IS_IN_TFIDF_INDEX BOOLEAN,
    TO_FETCH BOOLEAN
) TABLESPACE mydbspace;



CREATE TABLE IF NOT EXISTS CATEGORY_BAG_OF_WORDS (
    CATEGORY VARCHAR(400),
    BLOBOID OID,
    LAST_UPDATE DATE
) TABLESPACE mydbspace;